[tool.poetry]
name = "wwm"
version = "0.1.0"
description = ""
authors = ["Sam <sam.thompson@biarri.com>"]

[tool.poetry.dependencies]
python = "3.8.2"
pytest = "^5.4.1"
numpy = "^1.18.3"
pyproj = "^2.6.1"
cfgrib = "^0.9.8"
xarray = "^0.16.0"
pandas = "^1.0.5"
ipdb = "^0.13.3"
flask = "^1.1.2"
flask_restful = "^0.3.8"
webargs = "^6.1.0"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
